ListenIp="0.0.0.0"
ListenPort=18080

# 双机冗余，也可部署一个节点，随机数均衡法
[RocketMq]
#NameServers=["127.0.0.1:9876","127.0.0.1:9876"]
ConsumeGroup="cim_job_consumer_group1"
NameServers=["10.0.107.218:9876"]

[[Gate]]
Ip="127.0.0.1"
Port=7900
MaxConnCnt=4                # 2的整数倍

#[[Gate]]
#Ip="127.0.0.1"
#Port=7900
#MaxConnCnt=4                # 2的整数倍