ListenIp="0.0.0.0"
ListenPort=10600

# 主库，读写，优先写
[[Db]]
ServerName="Master"
#Host="127.0.0.1"
Host="106.14.172.35"
Port=13306
DbName="coffeechat"
UserName="cim"
Password="12345"
MaxConnCnt=16

# 从库，只读
# 可以和主库保持一致，这样则意味着不使用主从模式，此时，建议把maxconncnt调小一倍
[[Db]]
ServerName="Slave"
#Host="127.0.0.1"
Host="106.14.172.35"
Port=13306
DbName="coffeechat"
UserName="cim"
Password="12345"
MaxConnCnt=16

[RocketMq]
Enable=true # 是否启用rocketmq，如果需要部署多台gate，则需要打开
#NameServers=["127.0.0.1:9876","127.0.0.1:9876"]
NameServers=["10.0.107.218:9876"]

[Redis]
Name="cim"
#Ip="127.0.0.1"
Ip="106.14.172.35"
Port=6379
KeyPrefix="cim|"        # redis中key的统一前缀
Password="coffeechat"   # redis的密码，不允许为空

[[Redis.Pool]]
Name="unread"
DbNum=1
MaxConnect=64

[[Redis.Pool]]
Name="msgid"            # 消息序号ID
DbNum=2
MaxConnect=16

[[Redis.Pool]]
Name="online_user_hash" # 存储用户在线状态
DbNum=3
MaxConnect=16
