[Db]
    [Db.Master]
    host="127.0.0.1"
    port=3306
    dbname="coffeechat"
    username="test"
    password="123456"
    maxconncnt=16

    [Db.Slave]
    host="127.0.0.1"
    port=3306
    dbname="coffeechat"
    username="test"
    password="123456"
    maxconncnt=16