ListenIp="127.0.0.1"
ListenPort=10600

[[Db]]
# 主库，读写，优先写
ServerName="Master"
Host="127.0.0.1"
Port=3306
DbName="coffeechat"
UserName="test"
Password="123456"
MaxConnCnt=16

[[Db]]
# 从库，只读
# 可以和主库保持一致，这样则意味着不使用主从模式，此时，建议把maxconncnt调小一倍
ServerName="Slave"
Host="127.0.0.1"
Port=3306
DbName="coffeechat"
UserName="test"
Password="123456"
MaxConnCnt=16

[Kafka]
# Topic由前缀+cmdID组成，如msg_data消息id为301，则Topic=CoffeeChat_301
TopicPrefix="CoffeeChat_"
Brokers= ["10.0.59.231:9092"]