ListenIp="0.0.0.0"    # 任意，如果绑定2个网卡，理论上可以支持65535*2的连接
ListenPort=8500

# minio server
[MinIo]
Ip="10.0.59.231"
Port=9000
AccessKeyID="minioadmin"
SecretAccessKey="minioadmin"
UseSSL=false
Location="us-east-1"